const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ts=require(process.env.DIPLAY_TYPESCRIPT||'typescript');
function load(name,deps={},ext='.ts',globals={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(__dirname+'/../entry/src/main/ets/lab/'+name+ext,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,Uint8Array,DataView,setInterval,clearInterval,require:id=>id==='./DisplayProfile'?profile:deps[id],...globals});return exports;}
const profile=load('DisplayProfile'),core=load('PairingCore'),plist=load('Bplist',{'./PairingCore':core}),receiver=load('ReceiverInfo',{'./Bplist':plist}),hid=load('HidTouch',{'./Bplist':plist});
const {displayProfile,DisplayProfile,fitVideo}=profile;let count=0;
async function check(name,fn){await fn();count++;console.log('PASS '+name);}
(async()=>{
await check('16:10 panel requests 1280x800 without changing pixel aspect',()=>{const p=displayProfile(2560,1600,343,343);assert.equal(p.width,1280);assert.equal(p.height,800);assert.equal(p.physicalWidth,190);assert.equal(p.physicalHeight,118);assert.equal(p.measuredPpi,true);assert.deepEqual([...fitVideo(1078,674,p)],[1078,673.75]);});
await check('portrait display metrics preserve the landscape axes and physical dimensions',()=>{const a=displayProfile(2560,1600,350,340),b=displayProfile(1600,2560,340,350);for(const key of ['width','height','physicalWidth','physicalHeight','panelWidth','panelHeight'])assert.equal(a[key],b[key]);});
await check('unavailable physical PPI uses proportional estimate; invalid panel keeps compatible default',()=>{const p=displayProfile(2560,1600,0,NaN);assert.equal(p.measuredPpi,false);assert.equal(p.physicalWidth,180);assert.equal(p.physicalHeight,113);for(const [w,h]of [[0,0],[NaN,1600],[2560,Infinity],[99999,99999]]){const d=displayProfile(w,h,343,343);assert.equal(d.width,1280);assert.equal(d.height,720);}});
await check('16:9 and 4:3 hardware retain their own ratios with even bounded stream sizes',()=>{for(const [w,h]of [[1920,1080],[2048,1536],[2732,2048],[800,600]]){const p=displayProfile(w,h,320,320);assert.ok(p.width<=1280);assert.equal(p.width%2,0);assert.equal(p.height%2,0);assert.ok(Math.abs(p.width/p.height-w/h)<.005);}});
await check('display, view area and safe area expose one consistent 16:10 geometry',()=>{const p=displayProfile(2560,1600,343,343),info=receiver.receiverInfo('00:11:22:33:44:55',false,p),d=info.entries.get('displays').items[0],view=d.entries.get('viewAreas').items[0],safe=view.entries.get('safeArea');for(const item of [d,view,safe]){assert.equal(item.entries.get('widthPixels').number(),1280);assert.equal(item.entries.get('heightPixels').number(),800);}assert.equal(d.entries.get('widthPhysical').number(),190);assert.equal(d.entries.get('heightPhysical').number(),118);
const bytes=info.entries.get('hidDevices').items[0].entries.get('hidDescriptor').data;const bounds=[];for(let i=0;i<bytes.length-2;i++)if(bytes[i]===38)bounds.push(bytes[i+1]+256*bytes[i+2]);assert.deepEqual(bounds,[1280,800,1280,800]);});
await check('bottom-right touch and release use negotiated HID maximum; center matches new height',()=>{const p=displayProfile(2560,1600,343,343);for(const down of [true,false]){const b=Buffer.from(hid.touchCommand(1,1,down,p).entries.get('hidReport').data);assert.equal(b.readUInt16LE(2),1280);assert.equal(b.readUInt16LE(4),800);assert.equal(b[1],down?1:0);}const b=Buffer.from(hid.touchCommand(.5,.5,true,p).entries.get('hidReport').data);assert.equal(b.readUInt16LE(4),400);});
await check('native decoder is started with the same dimensions, not the old 720-line size',()=>{const calls=[];const {VideoBridge}=load('VideoBridge',{'libdiplayvideo.so':{default:{start:(...args)=>{calls.push(args);return 0;},stop(){}}}},'.ets');const bridge=new VideoBridge();bridge.setSurface('123');const owner=bridge.claim(displayProfile(2560,1600,343,343));assert.deepEqual(calls,[['123',1280,800]]);bridge.release(owner);});
await check('phone aspect mismatch ends the stream instead of reporting successful stretched fullscreen',async()=>{let poll,rendered=0,ended=0,released=0;const messages=[],starts=[];
const {NativeScreenServer}=load('NativeScreenServer',{'./ScreenCodec':load('ScreenCodec',{'./PairingCore':core}),'./VideoBridge':{VideoBridge:{instance:{claim:p=>{starts.push(p);return 1;},stats:()=>[1,1,0,0,1280,720],release:()=>released++}}},'@kit.NetworkKit':{socket:{constructTCPSocketServerInstance:()=>({on(){},async listen(){},async getLocalAddress(){return {port:30000};},async close(){}})}}},'.ets',{setInterval:fn=>{poll=fn;return 1;},clearInterval(){}});
const p=displayProfile(2560,1600,343,343),server=new NativeScreenServer(new Uint8Array(32),{},m=>messages.push(m),()=>rendered++,()=>ended++,p);await server.start();poll();assert.equal(starts[0],p);assert.equal(rendered,0);assert.equal(ended,1);assert.equal(released,1);assert.ok(messages.some(m=>m.includes('比例与协商不一致')));await server.close();});
console.log(count+' display geometry tests passed');
})().catch(e=>{console.error(e);process.exitCode=1;});

